# @format

# Based on https://pre-commit.com
#image: python:alpine
image: pypy:latest
gitlab-ci-pre-commit:
  stage: build
  before_script:
    #- apk add --no-cache git gcc musl-dev go
    - pypy3 -m pip install pre-commit
  script:
    - pre-commit run --all-files --show-diff-on-failure
  variables:
    # Remember to gitignore .cache/**
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
    TERM: dumb
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
