# Black
[tool.black]
line-length = 79
target-version = ['py310']
preview = true

# Mypy
[tool.mypy]
python_version = '3.10'

# Pylint
[tool.pylint.main]
py-version = "3.10"
jobs = 0

[tool.pylint.basic]
include-naming-hint = true

[tool.pylint.format]
max-line-length = 79

[tool.pylint."messages control"]
# Disables warnings about TODO
disable = ["W0511"]

#[tool.pylint.variables]
#ignored-argument-names = "_.*|^ignored_|^unused_"

# https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html

# isort
[tool.isort]
profile = "black"
