# When changing this file, read also .pre-commit-config.yaml

[tool.black]
line-length = 79
target-version = ['py310']
preview = true

[tool.mypy]
#python-executable = 'pypy3'
python_version = '3.10'

# https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html

[tool.pylint.format]
max-line-length = 79

# Not actually used here, see .pre-commit-config.yaml for reorder-python-imports
# that does the same thing.
#[tool.isort]
#profile = "black"

# copy-pasted comments end.
