#!/usr/bin/env bash
set -x

if [ -f /etc/os-release ]; then
	. /etc/os-release
	if [ "$ID" == "arch" ]; then
		echo "Remember! sudo pacman -S fuse2"
	fi
fi

# This assumes the usage of GearLever with the default directory.
if [ -f ~/AppImages/beeper.appimage ]; then
	~/AppImages/beeper.appimage --ozone-platform=wayland --enable-features=WaylandWindowDecorations "$@"
# Or using Tails with portable installation
elif [ -f "$HOME/Persistent/AppImages/beeper.appimage" ]; then
	# Ensure it has the portable directory instead of thrwing the files on
	# temporary media
	mkdir -vp "$HOME/Persistent/AppImages/beeper.appimage.home"
	# We are using Tor, so we are American English, UTC is enforced anyway,
	# but probably won't hurt.
	export LC_ALL=en_US.utf8
	export TZ=UTC
	$HOME/Persistent/AppImages/beeper.appimage --ozone-platform=wayland --enable-features=WaylandWindowDecorations --proxy-server=socks5://127.0.0.1:9050 "$@"
else
	print "~/AppImages/beeper.appimage not found. Please install it through gearlever (default location) or symlink it there."
	notify-send "~/AppImages/beeper.appimage not found. Please install it through gearlever (default location) or symlink it there."
	if hash gearlever 2> /dev/null; then
		gearlever
	fi
fi
set +x
