#!/usr/bin/env bash
set -x

# This assumes the usage of GearLever with the default directory.
if [ -f ~/AppImages/beeper.appimage ]; then
	~/AppImages/beeper.appimage --ozone-platform=wayland --enable-features=WaylandWindowDecorations "$@"
else
	print "~/AppImages/beeper.appimage not found. Please install it through gearlever (default locaiton) or symlink it there."
	notify-send "~/AppImages/beeper.appimage not found. Please install it through gearlever (default locaiton) or symlink it there."
	if hash gearlever 2> /dev/null; then
		gearlever
	fi
fi
set +x
