#!/usr/bin/env bash
set -x

if [[ -d "$HOME/.config/BraveSoftware/Brave-Browser-Nightly" && -d "$HOME/.cache/BraveSoftware/Brave-Browser-Nightly" ]]; then
	/usr/bin/brave-browser-nightly --ozone-platform=wayland --disk-cache-dir='/dev/null' --enable-features=WaylandWindowDecorations "$@"
elif [ -f /usr/bin/brave-browser-stable ]; then
	/usr/bin/brave-browser-stable --ozone-platform=wayland --disk-cache-dir='/dev/null' --enable-features=WaylandWindowDecorations "$@"
elif [ -f /var/lib/snapd/snap/bin/brave ]; then
	snap run brave --ozone-platform=wayland --disk-cache-dir='/dev/null' --enable "$@"
fi

set +x
