#!/usr/bin/env bash
set -x
# Fedora-only, Debian uses a different CPU limit implementation!
#cpulimit --lazy --include-children --limit=30 flatpak run org.briarproject.Briar//stable "$@"
systemd-run --scope -p CPUQuota="30%" --user flatpak run org.briarproject.Briar//stable "$@"
set +x
