#!/usr/bin/env bash

set -x
if [ -f /usr/bin/code ]; then
	/usr/bin/code --verbose --enable-features=WaylandWindowDecorations,UseOzonePlatform --ozone-platform=wayland "$@"

elif [ -f /var/lib/snapd/snap/bin/code ]; then
	# https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1951491/comments/104
	#unset DBUS_SESSION_BUS_ADDRESS
	# https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1951491/comments/105
	#export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus
	snap run code --verbose --enable-features=WaylandWindowDecorations,UseOzonePlatform --ozone-platform=wayland "$@"

elif [ -f ~/.local/share/flatpak/exports/bin/run/com.visualstudio.code ]; then
	flatpak run --user com.visualstudio.code --verbose --no-sandbox --ozone-platform=wayland --enable-features=WaylandWindowDecorations "$@"

elif [ -f /var/lib/flatpak/exports/bin/com.visualstudio.code ]; then
	flatpak run com.visualstudio.code --verbose --no-sandbox --ozone-platform=wayland --enable-features=WaylandWindowDecorations "$@"

else
	echo "code not found :("
fi
set +x
