#!/usr/bin/env bash

set -x
if [ -f /usr/bin/codium ]; then
	/usr/bin/codium --verbose --enable-features=WaylandWindowDecorations,UseOzonePlatform --ozone-platform=wayland "$@"

elif [ -f /snap/bin/codium ]; then
	# https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1951491/comments/104
	#unset DBUS_SESSION_BUS_ADDRESS
	# https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1951491/comments/105
	#export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus
	snap run codium --verbose --enable-features=WaylandWindowDecorations,UseOzonePlatform --ozone-platform=wayland "$@"

elif [ -f ~/.local/share/flatpak/exports/bin/run/com.vscodium.codium ]; then
	flatpak run --user com.vscodium.codium --verbose --no-sandbox --ozone-platform=wayland --enable-features=WaylandWindowDecorations "$@"

elif [ -f /var/lib/flatpak/exports/bin/com.vscodium.codium ]; then
	flatpak run com.vscodium.codium --verbose --no-sandbox --ozone-platform=wayland --enable-features=WaylandWindowDecorations "$@"

else
	echo "codium not found :("
fi
set +x
