#!/usr/bin/env bash

# Run under flatpak, and Wayland

set -x
# https://github.com/flathub/com.vscodium.codium/issues/55
flatpak run com.vscodium.codium --no-sandbox --enable-features=UseOzonePlatform --ozone-platform=wayland $@
set +x
