#!/usr/bin/env bash

# The usual Electron flags: --disable-gpu --enable-features=UseOzonePlatform,WaylandWindowDecorations,WebRTCPipeWireCapturer --ozone-platform=wayland

# https://github.com/deltachat/deltachat-desktop/issues/2800
# Wayland would be enabled by: --enable-features=UseOzonePlatform,WaylandWindowDecorations,WebRTCPipeWireCapturer --ozone-platform=wayland

set -x
flatpak run chat.delta.desktop --disable-gpu $@
set +x
