#!/usr/bin/env bash

# Wayland flags:  --enable-features=UseOzonePlatform,WaylandWindowDecorations,WebRTCPipeWireCapturer --ozone-platform=wayland
# Wayland crash: https://github.com/vector-im/element-web/issues/19964
# Crash workaround for Signal-desktop, but not Element? --disable-gpu

set -x
# Flatpak is preferred for Element not having official Fedora repositories
# and at the time of writing being unmaintained in upstream suggested repo.
flatpak run im.riot.Riot $@
set +x
