#!/usr/bin/env bash

set -x
# proxy authentication is not supported
# https://github.com/vector-im/element-web/issues/3320
flatpak run --env=LC_ALL=en_US.utf8 --env=TZ=UTC im.riot.Riot --proxy-server=socks5://127.0.0.1:9050 --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations "$@"
set +x
