#!/usr/bin/env bash

# This is variant of the firefox wrapper script, except without profile
# manager for use with desktop entry that just quickly launches the main
# profile.

set -x
export MOZ_ENABLE_WAYLAND=1
FlagsForFirefox="--allow-downgrade $@"

# Firefox (stable, beta) and signatures: https://releases.mozilla.org/pub/firefox/releases/
# Developer edition (and signatures): https://releases.mozilla.org/pub/devedition/releases/
if [ -f ~/.local/firefox/firefox ]; then
	~/.local/firefox/firefox $FlagsForFirefox
# Fallback to global installation
elif [ -f /usr/bin/firefox ]; then
	/usr/bin/firefox $FlagsForFirefox
# Fallback to global installation
elif [ -f /usr/bin/firefox-esr ]; then
	/usr/bin/firefox-esr $FlagsForFirefox
# Fallback to Snap which apparently follows /etc/policies.json
elif [ -f /snap/bin/firefox ]; then
	snap run firefox $FlagsForFirefox
# Fallback to flatpak, don't care if it doesn't exist
else
	flatpak run org.mozilla.firefox $FlagsForFirefox
fi

set +x
