#!/usr/bin/env bash

# I always want to see the profile manager, whether it's my first run or
# not and I probably have to micromanage wayland enabling everywhere.

# I cannot use the Flatpak as it doesn't support smartcards.

set -x
export MOZ_ENABLE_WAYLAND=1
FlagsForFirefox="--ProfileManager $@"

# Firefox (stable, beta) and signatures: https://releases.mozilla.org/pub/firefox/releases/
# Developer edition (and signatures): https://releases.mozilla.org/pub/devedition/releases/
if [ -f ~/.local/firefox/firefox ]; then
	~/.local/firefox/firefox $FlagsForFirefox
# Fallback to global installation
elif [ -f /usr/bin/firefox ]; then
	/usr/bin/firefox $FlagsForFirefox
# Fallback to global installation
elif [ -f /usr/bin/firefox-esr ]; then
	/usr/bin/firefox-esr $FlagsForFirefox
# Fallback to flatpak, don't care if it doesn't exist
else
	flatpak run org.mozilla.firefox $FlagsForFirefox
fi

set +x
