#!/usr/bin/env bash

# Flutter doesn't support flatpak, so Snap is the least bad Fluffy experience.

set -x
if [ -f /snap/bin/fluffychat ]; then
	# https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1951491/comments/104
	unset DBUS_SESSION_BUS_ADDRESS
	snap run fluffychat $@
else
	/usr/bin/fluffychat
fi
set +x
