#!/usr/bin/env bash

# Flutter doesn't support flatpak, so Snap is the least bad Fluffy experience.

set -x
if [ -f /snap/bin/fluffychat ]; then
	# https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1951491/comments/104
	unset DBUS_SESSION_BUS_ADDRESS
	# I am supposed to be a Finnish localizer so my eo over fi as protest
	# doesn't work here!
	export LANGUAGE=fi:eo:en
	snap run fluffychat "$@"
else
	/usr/bin/fluffychat
fi
set +x
