#!/usr/bin/env bash

# Using the snap version of go if available

set -x

# Check if go is installed through snap
if [ -f /snap/bin/go ]; then
	snap run go $@

# Fallback to system installation
else
	/usr/bin/go $@
fi

set +x
