#!/usr/bin/env bash
# In case we are on SteamOS?
#set -x
# The usual system-wide installation
if [ -f /usr/bin/meld ]; then
	/usr/bin/meld $@
# System-wide flatpak
elif [ -f /var/lib/flatpak/exports/bin/org.gnome.meld ]; then
	flatpak run org.gnome.meld $@
# User-specific flatpak
elif [ -f ~/.local/share/flatpak/exports/bin/org.gnome.meld ]; then
	flatpak run --user org.gnome.meld $@
# If not found.
else
	printf "meld doesn't seem to be installed :("
fi
#set +x
