#!/usr/bin/env bash
set -x

FlagsForChromium="--ozone-platform=wayland --disk-cache-dir=/dev/null --enable-features=WaylandWindowDecorations --disable-features=ExtensionManifestV2Unsupported,ExtensionManifestV2Disabled $@"

/usr/bin/microsoft-edge $FlagsForChromium
set +x
