#!/usr/bin/env bash

# To run Microsoft Edge under Wayland
# with Mullvad proxy
# Wireguard:  --proxy-server=socks5://10.64.0.1
# OpenVPN: --proxy-server=socks5://10.8.0.1

set -x
/usr/bin/microsoft-edge --enable-features=UseOzonePlatform,WaylandWindowDecorations,WebRTCPipeWireCapturers,EncryptedClientHello,UseDnsHttpsSvcbAlpn --ozone-platform-hint=auto  $@
# --enable-features=VaapiVideoDecoder,VaapiIgnoreDriverCheck -ignore-gpu-blocklist --enable-gpu-rasterization --enable-zero-copy --disable-gpu-driver-bug-workarounds --enable-native-gpu-memory-buffers
set +x
