#!/usr/bin/env bash
# Nheko flatpak with Tor
# USAGE: "nheko default" for the default profile or whatever profile is
# desired
set -x
if [[ "$1" == -* ]]; then
	flatpak run --env=LC_ALL=C.utf8 --env=TZ=UTC --env=all_proxy=socks5://127.0.0.1:9050/ im.nheko.Nheko//master "$@"
else
	flatpak run --env=LC_ALL=C.utf8 --env=TZ=UTC --env=all_proxy=socks5://127.0.0.1:9050/ im.nheko.Nheko//master --compact --profile "$@"
fi
set +x
