#!/usr/bin/env bash

set -x
# proxy authentication is not supported
# https://github.com/vector-im/element-web/issues/3320
flatpak run --env=LC_ALL=C.utf8 --env=TZ=UTC chat.schildi.desktop --proxy-server=socks5://127.0.0.1:9050 --ozone-platform=wayland --enable-features=WaylandWindowDecorations --system-theme-dark-override "$@"
set +x
