#!/usr/bin/env bash

# Signal desktop with Wayland, notification fix & tray

set -x
# --start-in-tray - would be nice, but then I cannot open it from there, thus --use-tray-icon
(flatpak run org.signal.Signal --use-tray-icon --ozone-platform=wayland --enable-features=WaylandWindowDecorations "$@" &)
if [ -f /snap/bin/signal-desktop ]; then
	#snap set signal-desktop tray-icon=true
	(snap run signal-desktop --use-tray-icon --ozone-platform=wayland --enable-features=WaylandWindowDecorations "$@" &)
fi
set +x
