#!/usr/bin/env bash

# Starting Plasma in Wayland with proper environment too. My {bash,zsh}rc handles
# exec

set -x

# Using maliit
export XMODIFIERS=@im=maliit
export GTK_IM_MODULE="maliit"
export QT_IM_MODULE="maliit"

export QT_QPA_PLATFORMTHEME="kde"
# https://librewolf.net/docs/faq/#cant-open-links-with-librewolf-when-using-wayland
export GDK_BACKEND=wayland

# Ensuring Wayland gets used as per Arch Wiki
# 2021-02-28 https://wiki.archlinux.org/index.php/Wayland#GUI_libraries
export QT_QPA_PLATFORM=wayland
export CLUTTER_BACKEND=wayland
export SDL_VIDEODRIVER=wayland
# Electron
export ELECTRON_OZONE_PLATFORM_HINT=wayland
# Mozilla Products
export MOZ_ENABLE_WAYLAND=1

# If kmscon is installed, use its wrapper. Additionally ensure dbus is around.
if hash kmscon-launch-gui 2> /dev/null; then
	kmscon-launch-gui dbus-launch --exit-with-session startplasma-wayland "$@"
else
	dbus-launch --exit-with-session startplasma-wayland "$@"
fi

set +x
