#!/usr/bin/env bash

# Starting sway with proper environment too. My {bash,zsh}rc handles
# exec

set -x

# As this script is kind of login manager and upstream wants to externalize
# the task of telling Sway is used to it,  https://github.com/swaywm/sway/pull/4876#issuecomment-570790128
# This seems to be required by Firefox and many others.
# Don't listen to Waybar claiming this should be "Unity"
export XDG_CURRENT_DESKTOP=sway
# https://github.com/flameshot-org/flameshot/blob/master/docs/Sway%20and%20wlroots%20support.md
# mentions this
export XDG_SESSION_DESKTOP=sway

# Java applications under non-parenting window managers (incl. sway)
#  via https://github.com/simplex-chat/simplex-chat/issues/2889#issuecomment-1677272784
export _JAVA_AWT_WM_NONREPARENTING=1

# Using fcitx
export XMODIFIERS=@im=fcitx
export GTK_IM_MODULE="fcitx"
export QT_IM_MODULE="fcitx"

# qt6ct allows theme choosing
export QT_QPA_PLATFORMTHEME="qt6ct"
# https://librewolf.net/docs/faq/#cant-open-links-with-librewolf-when-using-wayland
export GDK_BACKEND=wayland
# Dark theme for GTK apps. Fedora: "adwaita-qt*"
# https://github.com/swaywm/sway/wiki/GTK-3-settings-on-Wayland
export GTK_THEME=Adwaita:dark

# Ensuring Wayland gets used as per Arch Wiki
# 2021-02-28 https://wiki.archlinux.org/index.php/Wayland#GUI_libraries
export QT_QPA_PLATFORM=wayland
export CLUTTER_BACKEND=wayland
export SDL_VIDEODRIVER=wayland
# Electron
export ELECTRON_OZONE_PLATFORM_HINT=wayland
# Mozilla Products
export MOZ_ENABLE_WAYLAND=1

# Ensures dbus is available. Fedora 40 seems to no longer require
# --unsupported-gpu on nvidia either.
#dbus-launch --exit-with-session sway --unsupported-gpu "$@"
dbus-launch --exit-with-session sway "$@"
set +x
