#!/usr/bin/env bash

# Starting Plasma in Wayland with proper environment too. My {bash,zsh}rc handles
# exec

set -x

# Using fcitx
export XMODIFIERS=@im=fcitx
export GTK_IM_MODULE="fcitx"
export QT_IM_MODULE="fcitx"

# qt5ct allows theme choosing
export QT_QPA_PLATFORMTHEME="qt5ct"
# https://librewolf.net/docs/faq/#cant-open-links-with-librewolf-when-using-wayland
export GDK_BACKEND=wayland

# Ensuring Wayland gets used as per Arch Wiki
# 2021-02-28 https://wiki.archlinux.org/index.php/Wayland#GUI_libraries
export QT_QPA_PLATFORM=wayland
export CLUTTER_BACKEND=wayland
export SDL_VIDEODRIVER=wayland
# Electron
export ELECTRON_OZONE_PLATFORM_HINT=wayland
# Mozilla Products
export MOZ_ENABLE_WAYLAND=1

dbus-launch --exit-with-session startplasma-wayland $@
set +x
