#!/usr/bin/env bash
mkdir -p ~/.backups
cd ~/.backups
mkdir -p lakka
cd lakka
rsync -Paz --exclude='~/.local/*' --exclude='~/.pyenv/*' --exclude='*git*' lakka:~/ .
cd ..
mkdir -p hilla
cd hilla
rsync -Paz --exclude='~/.local/*' --exclude='~/.pyenv/*' --exclude='*git*' hilla:~/ .
cd ..
