#!/usr/bin/env bash
set -x

# If you are using my zncmodules script, you might want to run it before running this...

## Debian 7 has too old clang so use this with it
#unset CC
#unset CXX

# znc directory is the cloned git repository (https://github.com/znc/znc.git)
cd znc
# to make sure that we have all changes
git pull
# to get submodules and their submodules, currently csocket
# that doesn't have submodules.
git submodule update --init --recursive

# build znc normally out-of-source (build/ directory)
./autogen.sh
mkdir -p build
cd build
../configure --enable-debug --enable-perl --enable-python --enable-swig --enable-tcl --enable-cyrus --prefix=$HOME/.local
# and here you run "make -j$(nproc)" while you are in the build/ directory.
