#!/usr/bin/env bash
# This script downloads external ZNC modules which I use.
set -x

# znc/ is the cloned git repostiory (https://github.com/znc/znc.git)
cd znc/modules
wget -Ncnv https://raw.githubusercontent.com/kylef/znc-contrib/master/privmsg.cpp
wget -Ncnv https://raw.githubusercontent.com/Zarthus/Code-Snippets/master/c++/znc-modules/ctcp_notifier.cpp
wget -Ncnv https://github.com/jpnurmi/znc-playback/raw/master/playback.cpp
wget -Ncnv https://github.com/jpnurmi/znc-chanfilter/raw/master/chanfilter.cpp
wget -Ncnv https://github.com/KindOne-/znc-modules/raw/master/modules/freenodeinfo.cpp
wget -Ncnv https://github.com/jpnurmi/znc-clientbuffer/raw/master/clientbuffer.cpp

# modpython
wget -Ncnv https://raw.githubusercontent.com/jreese/znc-push/python/push.py
wget -Ncnv https://github.com/Nothing4You/znc-modules/raw/master/kill_notice.py
wget -Ncnv https://github.com/jdarmst/znc-modules/raw/master/python/myinsanity.py
wget -Ncnv https://github.com/AwwCookies/ZNC-Modules/raw/master/Aka/Aka.py

# now you should compile znc normally or use zncconfigure in this
# repository.
